<?php

namespace ResourceCatalog\Model;

interface IResourceCatalogTypeEnName
{
    const TYPE_ENNAME = array(
        IResourceCatalog::TYPE['NULL'] => '',
        IResourceCatalog::TYPE['XBXZCF'] => 'xbxzcf',
        IResourceCatalog::TYPE['XBXZXK'] => 'xbxzxk',
        IResourceCatalog::TYPE['HEIMDFR'] => 'heimdfr',
        IResourceCatalog::TYPE['HEIMDZRR'] => 'heimdzrr',
        IResourceCatalog::TYPE['HMDFR'] => 'hmdfr',
        IResourceCatalog::TYPE['HMDZRR'] => 'hmdzrr',
        IResourceCatalog::TYPE['SFCYRYXX'] => 'sfcyryxx',
        IResourceCatalog::TYPE['LDMFXJGZZ'] => 'ldmfxjgzz',
        IResourceCatalog::TYPE['MBFQYML'] => 'mbfqyml',
        IResourceCatalog::TYPE['SHTTDJXX'] => 'shttdjxx',
        IResourceCatalog::TYPE['SHGW'] => 'shgw',
        IResourceCatalog::TYPE['SSZK'] => 'sszk',
        IResourceCatalog::TYPE['STWJ'] => 'stwj',
        IResourceCatalog::TYPE['WFCXYZ'] => 'wfcxyz',
        IResourceCatalog::TYPE['WFXFAQ'] => 'wfxfaq',
        IResourceCatalog::TYPE['WHGGAQ'] => 'whggaq',
        IResourceCatalog::TYPE['WPXS'] => 'wpxs',
        IResourceCatalog::TYPE['XSJMWL'] => 'xsjmwl',
        IResourceCatalog::TYPE['YXGZ'] => 'yxgz',
        IResourceCatalog::TYPE['ZZQMXD'] => 'zzqmxd',
        IResourceCatalog::TYPE['CXSFSCZTJBXX'] => 'cxsfscztjbxx',
        IResourceCatalog::TYPE['HQBZDLY'] => 'hqbzdly',
        IResourceCatalog::TYPE['KHTSSJ'] => 'khtssj',
        IResourceCatalog::TYPE['MSSCSHCSJZXX'] => 'msscshcsjzxx',
        IResourceCatalog::TYPE['MSSCSHZYZFWXX'] => 'msscshzyzfwxx',
        IResourceCatalog::TYPE['NDZJFWGZ'] => 'ndzjfwgz',
        IResourceCatalog::TYPE['QGMXD'] => 'qgmxd',
        IResourceCatalog::TYPE['QQGGSS'] => 'qqggss',
        IResourceCatalog::TYPE['RLJJZX'] => 'rljjzx',
        IResourceCatalog::TYPE['RSGJ'] => 'rsgj',
        IResourceCatalog::TYPE['SBYY'] => 'sbyy',
        IResourceCatalog::TYPE['CCJCJG'] => 'ccjcjg',
        IResourceCatalog::TYPE['GZRYXX'] => 'grryxx',
        IResourceCatalog::TYPE['YSZYZGZXX'] => 'yszyzgzxx',
        IResourceCatalog::TYPE['JSZGXX'] => 'jszgxx',
        IResourceCatalog::TYPE['LSZYZGZXX'] => 'lszyzgzxx',
        IResourceCatalog::TYPE['XYSFSQ'] => 'xysfsq',
        IResourceCatalog::TYPE['QYFRGGXYZHPJJG'] => 'qyfrggxyzhpjjg',
        IResourceCatalog::TYPE['QYGGXYXX'] => 'qyggxyxx',
        IResourceCatalog::TYPE['QYJTXYXX'] => 'qyjtxyxx',
        IResourceCatalog::TYPE['GRZZXKXX'] => 'grzzxkxx',
        IResourceCatalog::TYPE['QYJBXX'] => 'qyjbxx',
        IResourceCatalog::TYPE['QYHYSJ'] => 'qyhysj',
        IResourceCatalog::TYPE['XZCJ'] => 'xzcj',
        IResourceCatalog::TYPE['XZJDJC'] => 'xzjdjc',
        IResourceCatalog::TYPE['XZJL'] => 'xzjl',
        IResourceCatalog::TYPE['XZQR'] => 'xzqr',
        IResourceCatalog::TYPE['XZQZ'] => 'xzqz',
        IResourceCatalog::TYPE['LXGLZDZYMLXX'] => 'lxglzdzymlxx',
        IResourceCatalog::TYPE['XHQNSPCXSFYQZTXX'] => 'xhqnspcxsfyqztxx',
        //@position
        IResourceCatalog::TYPE['TEST'] => 'test'
    );
}
