<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['XLGLMFZHGGWYH'] => 'XLGLMFZHGGWYH',
        IUserGroup::ID['RMYHXLGLMZXZH'] => 'RMYHXLGLMZXZH',
        IUserGroup::ID['XLGLMWZZB'] => 'XLGLMWZZB',
        IUserGroup::ID['XLGLMWXCB'] => 'XLGLMWXCB',
        IUserGroup::ID['XLGLMZFW'] => 'XLGLMZFW',
        IUserGroup::ID['XLGLMZJRMFY'] => 'XLGLMZJRMFY',
        IUserGroup::ID['XLGLMRMJCY'] => 'XLGLMRMJCY',
        IUserGroup::ID['XLGLMJYJ'] => 'XLGLMJYJ',
        IUserGroup::ID['XLGLMKXJSJ'] => 'XLGLMKXJSJ',
        IUserGroup::ID['XLGLMGYHXXHJ'] => 'XLGLMGYHXXHJ',
        IUserGroup::ID['XLGLMGAJ'] => 'XLGLMGAJ',
        IUserGroup::ID['XLGLMMZJ'] => 'XLGLMMZJ',
        IUserGroup::ID['XLGLMSFJ'] => 'XLGLMSFJ',
        IUserGroup::ID['XLGLMCZJ'] => 'XLGLMCZJ',
        IUserGroup::ID['XLGLMRLZYHSHBZJ'] => 'XLGLMRLZYHSHBZJ',
        IUserGroup::ID['XLGLMZRZYJ'] => 'XLGLMZRZYJ',
        IUserGroup::ID['XLGLMZFHCXJSJ'] => 'XLGLMZFHCXJSJ',
        IUserGroup::ID['XLGLMNMJ'] => 'XLGLMNMJ',
        IUserGroup::ID['XLGLMSLJ'] => 'XLGLMSLJ',
        IUserGroup::ID['XLGLMLYCYJ'] => 'XLGLMLYCYJ',
        IUserGroup::ID['XLGLMSWUJ'] => 'XLGLMSWUJ',
        IUserGroup::ID['XLGLMWTLYGDJ'] => 'XLGLMWTLYGDJ',
        IUserGroup::ID['XLGLMHZGSJRGZBGS'] => 'XLGLMHZGSJRGZBGS',
        IUserGroup::ID['XLGLMXFJ'] => 'XLGLMXFJ',
        IUserGroup::ID['XLGLMSWJ'] => 'XLGLMSWJ',
        IUserGroup::ID['XLGLMYBJJ'] => 'XLGLMYBJJ',
        IUserGroup::ID['XLGLMYCZMJ'] => 'XLGLMYCZMJ',
        IUserGroup::ID['XLGLMYZGLJ'] => 'XLGLMYZGLJ',
        IUserGroup::ID['XLGLMJTYSGLJ'] => 'XLGLMJTYSGLJ',
        IUserGroup::ID['XLGLMSTHJJ'] => 'XLGLMSTHJJ',
        IUserGroup::ID['XLGLMWSJKWYH'] => 'XLGLMWSJKWYH',
        IUserGroup::ID['XLGLMYJGLJ'] => 'XLGLMYJGLJ',
        IUserGroup::ID['XLGLMSJJ'] => 'XLGLMSJJ',
        IUserGroup::ID['XLGLMSCJDGLJ'] => 'XLGLMSCJDGLJ',
        IUserGroup::ID['GGZYGLZX'] => 'GGZYGLZX',
        IUserGroup::ID['XLGLMDSJFZGLJ'] => 'XLGLMDSJFZGLJ',
        IUserGroup::ID['XLGLMNYJ'] => 'XLGLMNYJ',
    );
}
