<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'XLGLMFZHGGWYH' => 1,
        'RMYHXLGLMZXZH' => 2,
        'XLGLMWZZB' => 3,
        'XLGLMWXCB' => 4,
        'XLGLMZFW' => 5,
        'XLGLMZJRMFY' => 6,
        'XLGLMRMJCY' => 7,
        'XLGLMJYJ' => 8,
        'XLGLMKXJSJ' => 9,
        'XLGLMGYHXXHJ' => 10,
        'XLGLMGAJ' => 11,
        'XLGLMMZJ' => 12,
        'XLGLMSFJ' => 13,
        'XLGLMCZJ' => 14,
        'XLGLMRLZYHSHBZJ' => 15,
        'XLGLMZRZYJ' => 16,
        'XLGLMZFHCXJSJ' => 17,
        'XLGLMNMJ' => 18,
        'XLGLMSLJ' => 19,
        'XLGLMLYCYJ' => 20,
        'XLGLMSWUJ' => 21,
        'XLGLMWTLYGDJ' => 22,
        'XLGLMHZGSJRGZBGS' => 23,
        'XLGLMXFJ' => 24,
        'XLGLMSWJ' => 25,
        'XLGLMYBJJ' => 26,
        'XLGLMYCZMJ' => 27,
        'XLGLMYZGLJ' => 28,
        'XLGLMJTYSGLJ' => 29,
        'XLGLMSTHJJ' => 30,
        'XLGLMWSJKWYH' => 31,
        'XLGLMYJGLJ' => 32,
        'XLGLMSJJ' => 33,
        'XLGLMSCJDGLJ' => 34,
        'GGZYGLZX' => 35,
        'XLGLMDSJFZGLJ' => 36,
        'XLGLMNYJ' => 37,
    );
}
